### ISSUE TITLE
Slabs from other mods are not being placed vertically

### ISSUE THREAD

**Issue by DadoIrie** [Andrew6rant/Auto-Slabs#4] opened 2023-08-14 15:11 UTC
As the title says, slabs from other mods are not being placed vertically despite those having the placement overlay which auto slabs provides.
Yesterday tried with Consistency+ and for faster loading now a own instance with 2 smaller mods which provide slabs.
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/15b02289-baeb-48f1-bc46-ccdc853dd7ab)
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/cc60e65f-9cf1-4d14-92c5-31a6d4a894b6)

**Comment by Andrew6rant** [comment] 2023-08-14 16:57
D'oh! This is a combination of two issues, one which is totally my fault, and one which is bizarre and needs significantly more research.

If your blocks look like this:

![image](https://github.com/Andrew6rant/Auto-Slabs/assets/57331134/f7b21c05-2f01-4290-9bc6-5b00ba9131c5)

That is on me - my custom ARRP entrypoint doesn't inject the models late enough, the modded resources override it. That is easy enough to fix.

If your blocks do not have vertical states at all, *that* is a serious issue, and one that has me scratching my head. For some reason, the block registry is not being populated.

By itself, Frostbyte's Slabs and stairs works with AutoSlabs, and Consistency+ is the same. When combined, sometimes Frostbyte's slabs are not added to the registry, and sometimes C+'s slabs aren't added to the registry, and sometimes neither are added.

I have no idea why this is happening, and I don't think my mod is the cause. I will look into it further.

**Comment by DadoIrie** [comment] 2023-08-14 17:24
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/6fb297af-79bf-411e-86bc-c1d23818cdfa)
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/fd5227d9-db31-4d2f-a818-7a1ae927029e)
nope, no vertical state - screenshots show with side I've picked to place and on those slab is placed on the upper part - when placing on the other sides it places on the lower part the slab

also here I'm facing towards south 
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/e28d69bc-a33e-4075-8e97-2c514ed83d8b)

now if facing west it's the down and right side where it places the slabs up
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/38a5afc3-db67-45df-afec-a8cfc40507f7)

**Comment by Andrew6rant** [comment] 2023-08-14 18:10
I've registered a listener for blocks being added to the registry. This should solve the issue of the blockstates not being applied.

The models have been fixed with a custom event in my fork of ARRP. I'll use it internally until it gets merged into main.

**Closed as completed** 2023-08-14 18:11 UTC
Labels: Bug

**Comment by DadoIrie** [comment] 2023-08-14 18:17
does this mean later need to add ARRP too (when it's merged into main)?

**Comment by Andrew6rant** [comment] 2023-08-14 18:42
No. I include ARRP in the jar file of my mod. But, right now I've swapped it for my ARRP fork, since the base ARRP doesn't have the functionality I need at the moment.

I'm going to wait until ARRP merges my PR before releasing an update on CurseForge and Modrinth. But for now, if you wanted to, you could download the latest version of my mod from GitHub Actions: https://github.com/Andrew6rant/Auto-Slabs/actions

It is using my ARRP instead of the official, so just ignore some of the logger spam.

**Comment by DadoIrie** [comment] 2023-08-14 18:45
I forgot about the actions - did build it already myself

**Comment by Andrew6rant** [comment] 2023-08-16 04:16
Fixed in 1.0.1
